services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\IndexNow\:
    resource: '../Classes/*'

  # Called by makeInstance in TYPO3s DataHandler
  JWeiland\IndexNow\Hook\DataHandlerHook:
    public: true

  querybuilder.tx_indexnow_stack:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_indexnow_stack'

  JWeiland\IndexNow\Domain\Repository\StackRepository:
    arguments:
      $queryBuilder: '@querybuilder.tx_indexnow_stack'

  JWeiland\IndexNow\EventListener\RespectPagesWithNoIndexEventListener:
    tags:
      - name: event.listener
        event: JWeiland\IndexNow\Event\ModifyPageUidEvent

  # Register commands for indexnow
  JWeiland\IndexNow\Command\NotifySearchEngineCommand:
    tags:
      - name: 'console.command'
        command: 'indexnow:notify'
        schedulable: true
