services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\IndexNow\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Called by makeInstance in TYPO3s DataHandler
  JWeiland\IndexNow\Hook\DataHandlerHook:
    public: true

  JWeiland\IndexNow\EventListener\RespectPagesWithNoIndexEventListener:
    tags:
      - name: event.listener
        identifier: 'respectPagesWithNoIndexEventListener'
